from typing import List, Dict,Optional
from ragas.dataset_schema import SingleTurnSample


def sample_parser_for_evaluation(query: str,retriever_results : Dict[str,any], llm_response: Optional[str] = None ) -> SingleTurnSample:

    """
    Parses the vectorstore response to create a context string.

    Args:
        query (str): The input query for which a response is to be generated.
        retriever_results (Dict[str, any]): Dictionary containing retriever outputs.
        llm_response (Optional[str]): The response generated by the LLM.

    Returns:
        SingleTurnSample: An instance representing the evaluation sample.
    """
    # Extract just the document content from each result
    documents = [doc['document'] for doc_id,doc in retriever_results.items()]
    
    if llm_response:
        sample_doc  = SingleTurnSample(
            user_input=query,
            response=llm_response,
            retrieved_contexts=documents
        )
    else:
        sample_doc  = SingleTurnSample(
            user_input=query,
            retrieved_contexts=documents
        )
    
    return sample_doc


